services:
  - type: web
    name: schmidt-bot
    runtime: python
    pythonVersion: "3.11.4"
    buildCommand: |
      pip install --upgrade pip
      pip install wheel
      pip install -r requirements.txt